services:
  backend:
    build: ./backend
    container_name: prccd_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:16
    container_name: prccd_postgres
    environment:
      POSTGRES_DB: prccd_db
      POSTGRES_USER: prccd_user
      POSTGRES_PASSWORD: prccd_pass
    ports:
      - "5432:5432"
    volumes:
      - prccd_postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: prccd_mongodb
    ports:
      - "27017:27017"
    volumes:
      - prccd_mongo_data:/data/db

volumes:
  prccd_postgres_data:
  prccd_mongo_data: